services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    networks:
      - slon_net

    environment:
      POSTGRES_PASSWORD: postgres

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 80:80
    networks:
      - slon_net

    environment:
      PGADMIN_DEFAULT_EMAIL: test@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1234

networks:
  slon_net:
    driver: bridge
